# Generated by Django 2.0 on 2020-06-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('Admin5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsfinal.Admin')),
                ('palyerP6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsfinal.AddPlayer')),
            ],
        ),
    ]
