# Generated by Django 2.0 on 2020-06-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsfinal', '0002_shopp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopp',
            old_name='total',
            new_name='total1',
        ),
    ]
