# Generated by Django 2.0 on 2020-06-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsfinal', '0003_auto_20200624_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopp',
            old_name='total1',
            new_name='total',
        ),
    ]
