# Generated by Django 2.0 on 2020-06-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsfinal', '0004_auto_20200624_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopp',
            old_name='total',
            new_name='total1',
        ),
    ]
